### ISSUE TITLE
是否可以支持ssr订阅

### ISSUE THREAD

**Issue by kingsunsun2012** [Krazysdaki/ClashCS-Beta#1]
请问能否支持ssr

**Comment by Krazysdaki** [comment]
1. 在 [frainzy1477/clashrdev](https://github.com/frainzy1477/clashrdev) 处下载 `clashr-windows-amd64-v0.18.0.4.zip` 并解压，将 `.exe` 文件重命名为 `clash-windows-amd64.exe`，替换原 `Clash` 核心，即可支持 `SSR` 节点；
2. 在 https://clashr.tgbot.co/ui/ 将 `SSR` 订阅链接转换为 `Clash` 订阅链接（或配置文件），即可使用。
