### ISSUE TITLE
请求增加功能

### ISSUE THREAD

**Issue by XiaoTeemo** [Krazysdaki/ClashCS-Beta#2]
1. 增加中文版
2. 自动识别 32/64 位系统
3. 增加设置为系统代理功能

**Comment by Krazysdaki** [comment]
1. 文字不多，故暂不添加中文；
2. Clash 上游已经不提供 Windows-x86 Release，故不考虑32位系统；
3. 设为系统代理功能将在下次更新添加（咕咕咕）。

第二项功能可以考虑自行编译。
